### ISSUE TITLE
Subuid/subgid range size

### ISSUE THREAD

**Issue by orky-dev** [jbtrystram/immich-podman-systemd#11]
> cat >> /etc/subuid <<EOF
> immich:2000000:1000000
> EOF

What is the point of this large range? 1000000?
Is there a reason behind this number?

**Comment by orky-dev** [comment]
nvm

**Comment by QuLogic** [comment]
This is a bit high, to be honest. [Systemd's user page](https://systemd.io/UIDS-GIDS/) recommends 65536 for various reasons outlined there (though that's not directly the same as `subuid`/`subgid` since they seem to have some philosophical differences.) Besides, I think each container is either root or uses one or two IDs, so shouldn't be anywhere near 1000000.

**Comment by vozhyk-** [comment]
I was probably following a different guide - either [Gentoo's](https://wiki.gentoo.org/wiki/Subuid_subgid) or Ubuntu's (I can't find the latter now). As far as I understand, this might be useful for nested containers; but I haven't used any so far.
